language: node_js
node_js:
- '8'
cache:
- yarn
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_889fcfe41a2c_key -iv $encrypted_889fcfe41a2c_iv -in gcp-key.json.enc -out gcp-key.json -d
script:
- yarn install
- yarn build
deploy:
  - provider: gae
    skip_cleanup: true
    config: app-test.yaml
    keyfile: gcp-key.json
    project: javazone-web-test
    on: develop
  - provider: gae
    skip_cleanup: true
    config: app-prod.yaml
    keyfile: gcp-key.json
    project: javazone-web-prod
    on: master
