language: node_js
node_js:
- '8'
cache:
- yarn
notifications:
  email: false
script:
- yarn install
- yarn build
deploy:
  provider: gae
  skip_cleanup: true
  config: app-test.yaml
  keyfile: gcp-key-test.json
  project: javazone-web-test
  on: develop
before_install:
- openssl aes-256-cbc -K $encrypted_889fcfe41a2c_key -iv $encrypted_889fcfe41a2c_iv
  -in gcp-key-test.json.enc -out gcp-key-test.json -d
